  # The Caddy web server - a production-ready web server that automatically handles HTTPS.
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /opt/caddy/data:/data
      - /opt/caddy/config:/config
      # We share the list of users and groups (read only) with the web server container so that users and permissions match the host server.
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # The individual users' web folders.
      - /var/www:/var/www
    networks:
      - main
