name: pangolin
services:
  {{docker-compose-tunnel.yml}}
  
  # Fossorial's Pangolin - can provide tunneling and authentication, basically a self-hostable version of Cloudflare Tunnels. See: https://pangolin.net
  pangolin:
    image: docker.io/fosrl/pangolin:1.18.3
    container_name: pangolin
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 256m
    volumes:
      - /opt/pangolin/config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "10s"
      timeout: "10s"
      retries: 15
    networks:
      - main
  
  # Part of Fossorial's containerised Pangolin setup. A reverse proxy.
  traefik:
    image: docker.io/traefik:v3.6
    container_name: traefik
    restart: unless-stopped
    
    ports:
      - 443:443
      - 80:80
      
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - /opt/pangolin/config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - /opt/pangolin/config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - /opt/pangolin/config/traefik/logs:/var/log/traefik # Volume to store Traefik logs
    networks:
      - main
  
  # Guacd - The Apache Guacamole (web-based remote desktop) proxy daemon.
  # Note the lack of a database container instance, generally included in the standard containerised Guacamole setup.
  # This is because we are using our own custom authentication plugin to provide connection details for users logging in via Pangolin.
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped
    networks:
      - main
  
  # Guacamole Client - The Guacamole web interface, served at the "/desktop" endpoint.
  desktop:
    image: guacamole/guacamole:latest
    container_name: desktop
    restart: unless-stopped
    expose:
      - "8080"
    #ports:
      #- "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      HTTP_AUTH_ENABLED: "true"
      HTTP_AUTH_HEADER: Remote-User
      WEBAPP_CONTEXT: desktop
    depends_on:
      - guacd
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # /etc/guacamole is where the custom Java extension needs to be placed.
      - /etc/guacamole:/etc/guacamole
  
  {{docker-compose-ssh.yml}}
  
  {{docker-compose-calc.yml}}

  {{docker-compose-exams.yml}}
  
  # The rclone GUI interface, served at the "/rclone" endpoint. Our own custom router application routes requests to "/rclone" to the rclone GUI instance running on the appropriate user's desktop container.
  rclone:
    image: {{DOCKERRCLONEGUI_DOCKER_IMAGE}}
    command: /usr/local/bin/rcloneGUI
    container_name: rclonegui
    restart: unless-stopped
    expose:
      - "8090"
    networks:
      - main
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Our own Web Console server.
  webconsole:
    image: {{DOCKERWEBCONSOLE_DOCKER_IMAGE}}
    command: /usr/local/bin/webconsole --start --localOnly false --port 8080
    container_name: webconsole
    restart: unless-stopped
    networks:
      - main
    volumes:
      # We share the list of users and groups (read only) with the web server container so that Task execute permissions can work properly.
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # Mount Web Console's working folder to hold Tasks.
      - /etc/webconsole:/etc/webconsole
  
  # Our own custom Go web server. This basic server serves user websites directly from the "www" folder of their home folder. Although basic, it does include support for CGI.
  # This web server sits behind the Pangolin proxy, so only authenticated users can see other users' websites - handy for a private-ish community setup (a school or business).
  # Intended as a simple mechanism to get users started with being able to create a website. For a production ready web server, install the Caddy webserver vias the install script flag ("-run caddy").
  wwwserver:
    image: {{DOCKERWWWSERVER_DOCKER_IMAGE}}
    command: /usr/local/bin/wwwServer
    container_name: wwwserver
    restart: unless-stopped
    networks:
      - main
    volumes:
      # We share the list of users and groups (read only) with the web server container so that CGI execute permissions can work properly.
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      # The individual users' web folders.
      - /var/www:/var/www
      ## We mount the log files so that we can share those with individual user containers so that users can see any CGI errors.
      #- /var/log/apache2/access.log:/var/log/apache2/access.log
      #- /var/log/apache2/error.log:/var/log/apache2/error.log

  {{docker-compose-caddy.yml}}

# We have to create an explicitly named network, otheriwse automatic DNS resolution doesn't work with the default network when new containers are added via "docker run".
networks:
  main:
    driver: bridge
