#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# For debugging - start a full XFCE4 desktop environment.
startxfce4 &
# For debugging - start just the XFCE4 window manager.
#xfwm4 &

#openbox-session &

bash /home/$1/autoResize.sh &

# Loop as long as pgrep returns a non-zero exit code (process not found).
while ! pgrep -x xfce4-panel > /dev/null; do
    sleep 0.1 # High frequency check (100ms) to catch it quickly
done
#pkill -x xfce4-panel
xfconf-query -c xfce4-desktop -p /desktop-icons/style -n -t int -s 0



if [ ! -d ".wine/drive_c/Program Files/ExamPad+" ]; then
  # Run the (Windows) installer.
  wine msiexec /i ExamPad+.msi /qb
fi

if [ ! -f ".wine/drive_c/windows/Fonts/times.ttf" ]; then
  # Use Winetricks to install "corefonts".
  winetricks corefonts
fi

wine ".wine/drive_c/Program Files/ExamPad+/ExamPad+.exe"

## Start the log file, handy for debugging.
#echo "Starting ClassWiz Emulator..."  > ~/.local/state/xstartup.log 2>&1

# For debugging - have xdotool list all available named windows to the log file.
# xdotool search --all --name "." getwindowname %@ >> ~/.local/state/xstartup.log 2>&1

## Find the Window ID of the Activation Wizard, waiting until the window is open.
#WINID=$(xdotool search --sync --name "ClassWiz Emulator Subscription for fx-83/85GT X Activation Wizard") >> ~/.local/state/xstartup.log 2>&1
## Focus that window and send keys.
#xdotool windowfocus --sync $WINID key "Down" >> ~/.local/state/xstartup.log 2>&1
#xdotool windowfocus --sync $WINID key "Return" >> ~/.local/state/xstartup.log 2>&1

## Find the Window ID of the FX-83/85GT X Emulator, waiting until the window is open.
#sleep 1
#WINID=$(xdotool search --sync --name "fx-83/85GT X Emulator") >> ~/.local/state/xstartup.log 2>&1
## Focus that window and send keys.
#sleep 1
#xdotool windowfocus --sync $WINID key "alt+w" >> ~/.local/state/xstartup.log 2>&1
#sleep 2
#xdotool windowfocus --sync $WINID type "f" >> ~/.local/state/xstartup.log 2>&1

# For debugging - send a test string to the calculator.
# xdotool windowfocus --sync $WINID type "5318008" >> ~/.local/state/xstartup.log 2>&1

# Start a constant "null" process so the container doesn't exit.
tail -f /dev/null
