#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start the window manager.
#xfwm4 &
#startxfce4 &

if [ ! -d ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator" ]; then
    # Download the (windows) installer for the Casio FX-83GT / FX-85GT emulator.
    curl https://info.casio.co.uk/hubfs/CAL/Emulators/Install/ClassWiz%20Emulator%20Subscription%20for%20fx-83GT%20X_85GT%20X%20Ver.2.01_c.exe -o installer.exe
    wine installer.exe
fi

cd ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator"
wine "fx-83GT X_85GT X Emulator.exe" &

echo "One"  > /tmp/startup.log 2>&1

# Find the Window ID of the ClassWiz Emulator, waiting until the window is open.
WINID=$(xdotool search --sync --name "ClassWiz Emulator Subscription for fx-83/85GT X Activation Wizard") >> /tmp/startup.log 2>&1

echo "$WINID" >> /tmp/startup.log 2>&1

# Focus that window and send keys.
xdotool windowfocus --sync $WINID key "Down" >> /tmp/startup.log 2>&1
xdotool windowfocus --sync $WINID key "Return" >> /tmp/startup.log 2>&1

sleep 2
echo "Three" >> /tmp/startup.log 2>&1
xdotool search --all --name "." getwindowname %@ >> /tmp/startup.log 2>&1

# Start a constant "null" process so the container doesn't exit.
tail -f /dev/null
