#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start the XFCE4 desktop environment.
startxfce4 &

bash /home/$1/autoResize.sh &
xfconf-query -c xfce4-desktop -p /desktop-icons/style -n -t int -s 0
xfconf-query -c xfwm4 -p /general/workspace_count -s 1
xfconf-query -c xfce4-panel -p /panels/panel-1/plugin-ids -n -t int -s 1

if [ ! -d ".wine/drive_c/Program Files/ExamPad+" ]; then
  # Run the ExamPad+ (Windows) installer.
  wine msiexec /i ExamPad+.msi /qb
fi

if [ ! -f ".wine/drive_c/windows/Fonts/times.ttf" ]; then
  # Use Winetricks to install "corefonts".
  winetricks corefonts
fi

wine ".wine/drive_c/Program Files/ExamPad+/ExamPad+.exe"

# Start a constant "null" process so the container doesn't exit.
tail -f /dev/null
