#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# For debugging - start a full XFCE4 desktop environment.
# startxfce4 &
# For debugging - start just the XFCE4 window manager.
# xfwm4 &

#if [ ! -d ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator" ]; then
#    # Download the (windows) installer for the Casio FX-83GT / FX-85GT emulator.
#    curl https://info.casio.co.uk/hubfs/CAL/Emulators/Install/ClassWiz%20Emulator%20Subscription%20for%20fx-83GT%20X_85GT%20X%20Ver.2.01_c.exe -o installer.exe
#    wine installer.exe
#fi

#cd ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator"
#wine "fx-83GT X_85GT X Emulator.exe" &

## Start the log file, handy for debugging.
#echo "Starting ClassWiz Emulator..."  > ~/.local/state/xstartup.log 2>&1

# For debugging - have xdotool list all available named windows to the log file.
# xdotool search --all --name "." getwindowname %@ >> ~/.local/state/xstartup.log 2>&1

## Find the Window ID of the Activation Wizard, waiting until the window is open.
#WINID=$(xdotool search --sync --name "ClassWiz Emulator Subscription for fx-83/85GT X Activation Wizard") >> ~/.local/state/xstartup.log 2>&1
## Focus that window and send keys.
#xdotool windowfocus --sync $WINID key "Down" >> ~/.local/state/xstartup.log 2>&1
x#dotool windowfocus --sync $WINID key "Return" >> ~/.local/state/xstartup.log 2>&1

## Find the Window ID of the FX-83/85GT X Emulator, waiting until the window is open.
#sleep 1
#WINID=$(xdotool search --sync --name "fx-83/85GT X Emulator") >> ~/.local/state/xstartup.log 2>&1
## Focus that window and send keys.
#sleep 1
#xdotool windowfocus --sync $WINID key "alt+w" >> ~/.local/state/xstartup.log 2>&1
#sleep 2
#xdotool windowfocus --sync $WINID type "f" >> ~/.local/state/xstartup.log 2>&1

# For debugging - send a test string to the calculator.
# xdotool windowfocus --sync $WINID type "5318008" >> ~/.local/state/xstartup.log 2>&1

# Start a constant "null" process so the container doesn't exit.
tail -f /dev/null
