#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start the window manager.
xfwm4 &

if [ ! -d ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator" ]; then
    # Download the (windows) installer for the Casio FX-83GT / FX-85GT emulator.
    curl https://info.casio.co.uk/hubfs/CAL/Emulators/Install/ClassWiz%20Emulator%20Subscription%20for%20fx-83GT%20X_85GT%20X%20Ver.2.01_c.exe -o installer.exe
    wine installer.exe
fi

cd ".wine/drive_c/Program Files (x86)/CASIO/ClassWiz Emulator Subscription/fx-83GT X_85GT X Emulator"
wine "fx-83GT X_85GT X Emulator.exe"
#wine "fx-83GT X_85GT X Emulator.exe" & sleep 0.5 && wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz && wmctrl -r :ACTIVE: -e 0,0,0,-1,-1 --toggle,undecorated

tail -f /dev/null
